#alias
alias c="clear"
alias ya="yazi"
alias lgit="lazygit"

#prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '<%b>'
setopt PROMPT_SUBST
PROMPT='%1~${vcs_info_msg_0_}: '

#export
export PATH="$HOME/Documents/dotfiles/bin:$PATH"

#docker
dclaude() {
  docker run -it --rm \
    -v "$(pwd):$(pwd)" \
    -v "$HOME/.claude.json:/home/appuser/.claude.json" \
    -v "$HOME/.claude/settings.json:/home/appuser/.claude/settings.json" \
    --workdir "$(pwd)" \
    claude-code-sandbox \
    claude --dangerously-skip-permissions
}
